name: Parse Wishlists
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        bundler-cache: true
    - name: Checks and parses wishlists
      run: bundle exec ruby convert.rb
    - name: Commit report
      run: |
        git config --global user.name 'FilterBot'
        git config --global user.email 'your-username@users.noreply.github.com'
        git add dist

        if git diff-index --quiet HEAD --; then
          echo "No changes to push"
        else
          git commit -am "Automated report"
          git push
        fi
